---
name: test Go

on:
  push:
    branches: 
      - go_test
      - main
  pull_request:
    branches:
      - go_test
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: chng Branch
      uses: actions/checkout@v2
      with:
        ref: go_test

    - name: Lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0
        cd go_web                  
        golangci-lint run


#    - name: Build
#      run: go build -v ./...

#    - name: Test
#      run: go test -v ./...



#          stable: 'false'
