---
name: test Go

on:
  push:
    branches:
    - go_test

  pull_request:
    branches:
    - go_test    

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: pwd
      run: pwd
    - uses: actions/checkout@v2
      with:
        ref: go_test
    - name: pwd
      run: pwd        
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
        
    - name: pwd
      run: pwd
        
    - name: Lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0
        cd go_web
        pwd
        golangci-lint run

#    - name: Build
#      run: go build -v ./...

#    - name: Test
#      run: go test -v ./...



#          stable: 'false'
